name: crop-forecasting-env
dependencies:
  - python=3.10.*
  - pip
  - pandas
  - ipykernel
  - netCDF4
  - matplotlib
  - Jinja2
  - python-dotenv
  - seaborn
  - statsmodels
  - scikit-learn
  - rich
  - ipywidgets
  - pytorch::pytorch
  - pip:
    - xarray-spatial
    - odc-stac
    - rioxarray
    - pystac
    - ipyleaflet
    - stackstac
    - pystac-client
    - planetary-computer
    - wandb